application:
  authorization:
    secret: some-very-very-very-very-very-very-very-very-very-very-long-secret
    callbacks:
      - http://localhost:4080/authorize/callback
  security:
    encryption-key: some-encryption-key
    allowed-origins: http://localhost:4080
  two-factor:
    requirement: OPTIONAL

  services:
    keys:
      - name: Service 1
        value: some-very-very-very-very-long-api-key-1
      - name: Service 2
        value: some-very-very-very-very-long-api-key-2

  initialization:
    users:
      - username: user
        password: P@ssw0rd
        roles:
          - USER
      - username: admin
        password: P@ssw0rd
        roles:
          - ADMIN

spring:
  application:
    name: authentication-server-dev
  jpa:
    hibernate:
      ddl-auto: create